"""The textless design (mint/designs/textless.css): a legendary creature and a spell rendered through it and
compared against tests/golden/design-textless-*.png, the way test_golden does the M15 frame; and the css's
promises about the page read off the render itself -- the picture where the type bar and the text box were, the
glass title bar, the sweep at the foot's corners, the stamp's bite, the black foot -- so a golden regenerated by
mistake cannot pass a broken frame.

    MINT_UPDATE_GOLDEN=1 pytest -m render tests/test_design_textless.py
"""
import os
import re
import shutil

import pytest
from PIL import Image

from mint import frame
from tests.conftest import synthetic_card
from tests.test_golden import CARDS, DPI, GOLDEN, MEAN_TOL, OUTLIER_FRAC, OUTLIER_LEVEL, DotSymbols, compare

pytest.importorskip("playwright")

# a legendary mythic creature (the crown, the stamp's bite, the P/T plate: everything the foot has to make room
# for) and a common instant (nothing at the foot but the collector line)
TEXTLESS = {
    "legend": CARDS["legend"],
    "spell": dict(name="Fixture's Bolt", type_line="Instant", colors=["R"], mana_cost="{R}", rarity="common",
                  power=None, toughness=None, oracle_text="Fixture's Bolt deals 3 damage to any target.", flavor_text=None),
    "saga": CARDS["saga"],
}


@pytest.fixture(scope="module")
def browser():
    from mint.browser import Browser
    with Browser(DPI) as b:
        yield b


def render(name, art, tmp_path, browser):
    card = synthetic_card(**TEXTLESS[name])
    fonts_css = frame.local_fonts(tmp_path / "no-workspace-fonts")
    html = frame.build_html(card, symbols=DotSymbols(), art_url="file://" + art, theme="wizards", fonts_css=fonts_css,
                            set_size=len(TEXTLESS), maker="tester", year="2026", design="textless")
    assert "fonts.googleapis.com" not in html
    if name != "saga":  # a saga keeps M15 (frame.M15_LAYOUTS)
        assert " design-textless" in html and ".design-textless .art { height: 280.9px;" in html
    out = tmp_path / f"design-textless-{name}.png"
    return out, browser.render(html, out)


def px(im, x, y):
    """The pixel at card units (x, y) -- the page has 11 of bleed each side."""
    return im.getpixel((round((x + 11) * DPI / 100), round((y + 11) * DPI / 100)))


def rules(css):
    """(selector, declarations) for each rule of the css, comments stripped."""
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    return [(sel.strip(), body) for sel, body in re.findall(r"([^{}]+)\{([^{}]*)\}", css)]


def test_design_row():
    """The art the css asks for is the M15 window's width from its top to the foot's flat edge, 210.6 x 280.9
    (19.6-230.2 x 39.7-320.6); frame.DESIGNS carries the whole page provisionally until the merge sets it, so only
    the aspect is held to: a portrait a little narrower than 3:4 either way."""
    w, h, css = frame.DESIGNS["textless"]
    assert css == "textless.css" and abs(w / h - 210.6 / 280.9) < 0.03


def test_the_css_moves_or_hides_m15_pieces_and_leaves_the_rest_alone():
    """The design file grows the art and its plate to the foot, hides the type bar and the text box with their
    plates, moves the band's foot and turns the title bar to glass through its fill variable; it never touches
    the P/T plate, the stamp, the crown or the footer, and never repaints a bar's background -- the outline, caps
    and bevel are template.html's layers over the fill."""
    css = frame.design_css("textless")
    assert ".design-textless .pl-art { height: auto; bottom: 27px;" in css
    assert ".design-textless .typebar, .design-textless .pl-type, .design-textless .textbox, .design-textless .pl-text," in css
    for sel, body in rules(css):
        assert sel.startswith(".design-textless"), f"a rule outside the design's class: {sel}"
        last = sel.split()[-1]
        assert last not in (".pt", ".stamp", ".footer", ".name", ".type", ".cost", ".crown", ".crown-o", ".pl-crown",
                            ".pl-title"), f"restated: {sel}"
        if ".titlebar" in sel:
            assert "background" not in body and "border" not in body, f"the bar's own layers repainted: {sel}"


@pytest.mark.render
def test_page(art, tmp_path, browser):
    """What the css does, read off the render of the legend: the picture where M15's type bar and text box are, the
    title bar a dark glass with white lettering, the black foot from 323 with the sweep at its corners and the
    stamp's bite in the middle, the band still down the sides, the P/T plate at its M15 place."""
    out, sizes = render("legend", art, tmp_path, browser)
    im = Image.open(out).convert("RGB")
    assert im.size == (408, 558) and sizes["text"] == 12.6  # no rules text to shrink: the box is gone
    black = (0, 0, 0)

    def bright(p):
        return sum(p) > 90

    # the placeholder's gradient runs where M15's type bar (207), text box (230-320) and band foot (318) were
    for x, y in ((60, 207), (125, 207), (60, 260), (180, 300), (90, 318), (200, 318)):
        assert bright(px(im, x, y)) and px(im, x, y) != black, (x, y, px(im, x, y))
    # the title bar's face is dark glass: the placeholder's vivid wash greyed by the 70% grey over it (its channels
    # within 40 of each other where the picture's are 100 apart), neither black nor the M15 bar's pale fill, and
    # its lettering is white
    face, below = px(im, 175, 27), px(im, 175, 60)
    assert 90 < sum(face) < 450 and max(face) - min(face) < 40 < max(below) - min(below), (face, below)
    assert any(sum(px(im, x, 27)) > 600 for x in range(22, 100)), "no white lettering in the title bar"
    # the black foot from 323 (the collector line's ground), and the sweep: black outside the curve at the left
    # corner (the P/T plate covers the right one on a creature), the picture inside it
    for x, y in ((60, 326), (125, 335), (170, 326), (5, 340), (245, 360), (14, 318), (20, 322), (28, 323), (239, 318)):
        assert px(im, x, y) == black, (x, y, px(im, x, y))
    for x, y in ((40, 316), (60, 319), (190, 319)):
        assert bright(px(im, x, y)) and px(im, x, y) != black, (x, y, px(im, x, y))
    # the stamp's bite: black between the picture's arc and the stamp at the card's middle
    assert px(im, 125, 318) == black and bright(px(im, 125, 312)), (px(im, 125, 318), px(im, 125, 312))
    # the band still runs down the sides beside the picture (M15's 10-16.6) and the border outside it
    assert px(im, 5, 200) == black and bright(px(im, 12, 200)) and px(im, 12, 200) != px(im, 60, 200)
    # the P/T plate where M15 puts it (310.5-330.5, right edge 235.7): its face over the foot's black
    assert bright(px(im, 225, 327)) and px(im, 225, 327) != px(im, 225, 300), (px(im, 225, 327), px(im, 225, 300))


@pytest.mark.render
def test_layouts_stay_m15(art, tmp_path, browser):
    """A saga in the design renders the M15 frame: its text box is still there."""
    out, sizes = render("saga", art, tmp_path, browser)
    im = Image.open(out).convert("RGB")
    assert sizes["text"] == 9.6 and px(im, 60, 250) != (0, 0, 0)


@pytest.mark.render
@pytest.mark.parametrize("name", ["legend", "spell"])
def test_golden(name, art, tmp_path, browser):
    out, _ = render(name, art, tmp_path, browser)
    golden = GOLDEN / f"design-textless-{name}.png"
    if os.environ.get("MINT_UPDATE_GOLDEN"):
        GOLDEN.mkdir(exist_ok=True)
        shutil.copy(out, golden)
        return
    assert golden.exists(), f"no golden for {name}; create it with MINT_UPDATE_GOLDEN=1 ({golden})"
    mean, outliers, diff = compare(out, golden)
    if mean >= MEAN_TOL or outliers >= OUTLIER_FRAC:
        diff_fn = tmp_path / f"design-textless-{name}.diff.png"
        diff.point(lambda v: min(255, v * 4)).save(diff_fn)
        pytest.fail(f"{name} differs from {golden}: mean |diff| {mean:.3f} (limit {MEAN_TOL}), "
                    f"{outliers:.2%} of pixels off by more than {OUTLIER_LEVEL} (limit {OUTLIER_FRAC:.1%}). "
                    f"render: {out}  diff: {diff_fn}")
