"""The borderless design (mint/designs/borderless.css): a creature and a basic land rendered through it and
compared against tests/golden/design-borderless-*.png, the way test_golden does the M15 frame; and the css's
promises about the page checked on the render itself -- art in the bleed, the bars where M15 has them, the plate
where the band was, the crown ending at the bar, the black foot -- so a golden regenerated by mistake cannot pass a
broken frame.

    MINT_UPDATE_GOLDEN=1 pytest -m render tests/test_design_borderless.py
"""
import os
import shutil

import pytest
from PIL import Image

from mint import frame
from tests.conftest import synthetic_card
from tests.test_golden import CARDS, DPI, GOLDEN, MEAN_TOL, OUTLIER_FRAC, OUTLIER_LEVEL, DotSymbols, compare

pytest.importorskip("playwright")


@pytest.fixture(scope="module")
def browser():
    from mint.browser import Browser
    with Browser(DPI) as b:
        yield b


BASIC = dict(name="Proving Forest", type_line="Basic Land — Forest", colors=[], mana_cost="", rarity="common",
             power=None, toughness=None, oracle_text="({T}: Add {G}.)", flavor_text=None, produced_mana=["G"])
LAYOUTS = {"legend": CARDS["legend"], "basic": BASIC, "saga": CARDS["saga"]}


def render(name, art, tmp_path, browser):
    card = synthetic_card(**LAYOUTS[name])
    fonts_css = frame.local_fonts(tmp_path / "no-workspace-fonts")
    html = frame.build_html(card, symbols=DotSymbols(), art_url="file://" + art, theme="wizards", fonts_css=fonts_css,
                            set_size=len(LAYOUTS), maker="tester", year="2026", design="borderless")
    assert "design-borderless" in html and "the picture under everything" in html  # the class, and the css with it
    out = tmp_path / f"design-borderless-{name}.png"
    return out, browser.render(html, out)


def px(im, x, y):
    """The pixel at card units (x, y) -- the page has 11 of bleed each side."""
    return im.getpixel((round((x + 11) * DPI / 100), round((y + 11) * DPI / 100)))


def test_design_row():
    w, h, css = frame.DESIGNS["borderless"]
    assert css == "borderless.css" and abs(w / h - 272 / 206) < 0.05  # the css covers the page's top 206


@pytest.mark.render
def test_page(art, tmp_path, browser):
    """What the css does, read off the render: no black anywhere the art should be, the bars where measured."""
    out, sizes = render("legend", art, tmp_path, browser)
    im = Image.open(out).convert("RGB")
    assert im.size == (408, 558) and sizes["text"] == 12.6
    # the art fills the bleed and the corners above the foot: the gradient placeholder is never black there,
    # M15's border is
    for x, y in ((-10, -10), (-10, 100), (259, 100), (-10, 250), (259, 250), (125, -10), (5, 60), (245, 190)):
        assert sum(px(im, x, y)) > 60, (x, y, px(im, x, y))
    # the title bar's face where M15 has it (17-37.2), the picture above its ring (15) and below it (39)
    face = px(im, 175, 27)
    assert sum(face) > 500 and abs(sum(px(im, 175, 31)) - sum(face)) < 40, (face, px(im, 175, 31))
    for y in (12, 41):
        assert sum(px(im, 175, y)) < 500 and px(im, 175, y) != face, (y, px(im, 175, y))
    # the crown ends at the bar's foot: M15's tongue beside the art (x 13.5-16.6, to 58, its outline out to
    # 10.8) is gone, so those pixels are the picture, not the outline's black or the badge's flat colour
    for x, y in ((12, 44), (15, 50), (235, 50)):
        assert px(im, x, y) != (0, 0, 0) and sum(px(im, x, y)) > 60, (x, y, px(im, x, y))
    # the plate beside the text box is flat pinline colour where M15 has the textured band -- read at the pinline
    # rectangle's own edge (17.5), since the pinline layer's shade falls on the plate's 15.4-16.6 as it falls on
    # M15's band -- and the same colour 2 under the box; a unit of black outside it; beyond, the picture's wash,
    # not black; and the collector line prints on a black foot
    plate = px(im, 17.5, 260)
    assert plate == px(im, 17.5, 290) == px(im, 60, 324), (plate, px(im, 17.5, 290), px(im, 60, 324))
    assert px(im, 14.5, 260) == (0, 0, 0) and px(im, 60, 326) == (0, 0, 0), (px(im, 14.5, 260), px(im, 60, 326))
    assert sum(px(im, 12, 260)) > 60 and px(im, 12, 260) != plate, px(im, 12, 260)
    for x, y in ((5, 335), (-5, 360), (125, 345), (259, 359)):
        assert px(im, x, y) == (0, 0, 0), (x, y, px(im, x, y))


@pytest.mark.render
def test_layouts_stay_m15(art, tmp_path, browser):
    """A saga in the design renders the M15 frame: the black border is still there."""
    out, _ = render("saga", art, tmp_path, browser)
    im = Image.open(out).convert("RGB")
    assert px(im, 5, 100) == (0, 0, 0) and px(im, 5, 5) == (0, 0, 0)


@pytest.mark.render
@pytest.mark.parametrize("name", ["legend", "basic"])
def test_golden(name, art, tmp_path, browser):
    out, _ = render(name, art, tmp_path, browser)
    golden = GOLDEN / f"design-borderless-{name}.png"
    if os.environ.get("MINT_UPDATE_GOLDEN"):
        GOLDEN.mkdir(exist_ok=True)
        shutil.copy(out, golden)
        return
    assert golden.exists(), f"no golden for {name}; create it with MINT_UPDATE_GOLDEN=1 ({golden})"
    mean, outliers, diff = compare(out, golden)
    if mean >= MEAN_TOL or outliers >= OUTLIER_FRAC:
        diff_fn = tmp_path / f"design-borderless-{name}.diff.png"
        diff.point(lambda v: min(255, v * 4)).save(diff_fn)
        pytest.fail(f"{name} differs from {golden}: mean |diff| {mean:.3f} (limit {MEAN_TOL}), "
                    f"{outliers:.2%} of pixels off by more than {OUTLIER_LEVEL} (limit {OUTLIER_FRAC:.1%}). "
                    f"render: {out}  diff: {diff_fn}")
